// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManagementInduvidualProject.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Laptop",
                            Price = 899.99m,
                            ProductCode = "P0001",
                            Quantity = 8
                        },
                        new
                        {
                            Id = 2,
                            Name = "Wireless Mouse",
                            Price = 29.99m,
                            ProductCode = "P0002",
                            Quantity = 25
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mechanical Keyboard",
                            Price = 79.99m,
                            ProductCode = "P0003",
                            Quantity = 15
                        },
                        new
                        {
                            Id = 4,
                            Name = "Monitor",
                            Price = 249.99m,
                            ProductCode = "P0004",
                            Quantity = 12
                        },
                        new
                        {
                            Id = 5,
                            Name = "USB-C Cable",
                            Price = 14.99m,
                            ProductCode = "P0005",
                            Quantity = 50
                        },
                        new
                        {
                            Id = 6,
                            Name = "Office Chair",
                            Price = 199.99m,
                            ProductCode = "P0006",
                            Quantity = 6
                        },
                        new
                        {
                            Id = 7,
                            Name = "Webcam",
                            Price = 59.99m,
                            ProductCode = "P0007",
                            Quantity = 18
                        },
                        new
                        {
                            Id = 8,
                            Name = "External SSD",
                            Price = 119.99m,
                            ProductCode = "P0008",
                            Quantity = 10
                        },
                        new
                        {
                            Id = 9,
                            Name = "Headset",
                            Price = 69.99m,
                            ProductCode = "P0009",
                            Quantity = 20
                        },
                        new
                        {
                            Id = 10,
                            Name = "Desk Lamp",
                            Price = 39.99m,
                            ProductCode = "P0010",
                            Quantity = 14
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
